<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-IHD58UK" ignored="1" name="Personal Loan" tests="5" failures="1" timestamp="13 Aug 2020 11:20:04 GMT" time="0.079" errors="0">
  <testcase name="Demo" time="0.012" classname="TestTestNg.Day1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestTestNg.Day1.Demo(Day1.java:21)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase name="ploan" time="0.002" classname="TestTestNg.Day2"/>
  <testcase name="LoginApihomeloan" time="0.001" classname="TestTestNg.Day4"/>
  <testcase name="Mobileloginhomeloan" time="0.002" classname="TestTestNg.Day4"/>
  <testcase name="Webloginhomeloan" time="0.003" classname="TestTestNg.Day4"/>
  <testcase name="Secondtest" time="0.0" classname="TestTestNg.Day1">
    <ignored/>
  </testcase> <!-- Secondtest -->
</testsuite> <!-- Personal Loan -->
